services:
  elasticsearch:
    image: elasticsearch:8.2.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"]
      interval: 30s
      timeout: 10s
      retries: 3
  tester:
    build:
      dockerfile: ./Dockerfile-3.9
    environment:
      PYGEOFILTER_ELASTIC_HOST: elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
